### ISSUE TITLE
Prod ready ?

### ISSUE THREAD

**Issue by pascalandy** [kaustavb12/rexray-plugin-installer#4]
I saw your project [from here](https://github.com/BretFisher/dogvscat/pull/29). How confident are you to use this project in prod ?

Thanks

**Comment by kaustavb12** [comment]
Hi @pascalandy 

I have tested the tool for different scenarios and have not found any issues.

Also have been using the tool using the DO driver extensively for an upcoming project of mine in pre-prod environments and it has worked without any problems.
The project is expected to go to production in a month and we are confident to use the tool in the prod environment too.

I must also mention that although I have tested the tool with the s3fs driver and have not found any issues, I have not used it as extensively in a running project.

Hope it helps.

**Comment by pascalandy** [comment]
Thanks for this detailed answer :)
Once the service is running, do you have docs to use the volume (or mount) ?

Thanks!

**Comment by kaustavb12** [comment]
The service from the [PR](https://github.com/BretFisher/dogvscat/pull/29) installs the rexray plugin in the node it is running in and then exits with the 'complete' state.

Volumes can then be created or mounted using the installed plugin driver as follows:

```
version: '3.8'

services:
  traefik:
    image: traefik:v2.4
    volumes:
      - traefik-public-certificates-do:/certificates
      # - traefik-public-certificates-aws:/certificates

    ...

volumes:
  traefik-public-certificates-do:
    driver: rexray/dobs
    driver_opts:
      size: 1
  # traefik-public-certificates-aws:
  #   driver: rexray/s3fs
  #   name: traefik-public-certificates-aws
```

Documentation about the driver options can be found here :
[https://rexray.readthedocs.io/en/stable/user-guide/schedulers/docker/#create-volume](https://rexray.readthedocs.io/en/stable/user-guide/schedulers/docker/#create-volume)

Also, docs about the env. variables used in it the script during plugin install can be found here: [DOBS](https://rexray.readthedocs.io/en/stable/user-guide/schedulers/docker/plug-ins/digitalocean/), [S3FS](https://rexray.readthedocs.io/en/stable/user-guide/schedulers/docker/plug-ins/aws/#simple-storage-service)
